version: '3'
services:
  nodejs:
    build: .
    container_name: nodejs
    ports:
      - '3000:3000'
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - '${MARIADB_PORT}:3306'
    volumes:
      - '${MARIADB_DATA}:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MARIADB_DATABASE}'
      MYSQL_USER: '${MARIADB_USER}'
      MYSQL_PASSWORD: '${MARIADB_PASSWORD}'
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MYSQL_USER: '${MARIADB_USER}'
      MYSQL_PASSWORD: '${MARIADB_PASSWORD}'
    ports:
      - '${PHPMYADMIN_PORT}:80'

  redis:
    container_name: 'redis'
    image: redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ${REDIS_DATA}:/data
    networks:
      - elasticnetwork

  elasticsearch:
    image: 'elasticsearch:7.13.3'
    container_name: 'elasticsearch'
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
    ports:
      - '${ELASTIC_PORT1}:9200'
      - '${ELASTIC_PORT2}:9300'
    volumes:
      - '${ELASTIC_CONFIG}:/usr/share/elasticsearch/config/elasticsearch.yml'
      - '${ELASTIC_DATA}:/usr/share/elasticsearch/data'
    networks:
      - elasticnetwork

  kibana:
    image: 'kibana:7.13.3'
    container_name: kibana
    ports:
      - '${KIBANA_PORT}:5601'
    volumes:
      - '${KIBANA_CONFIG}:/etc/kibana/kibana.yml'
    networks:
      - elasticnetwork
    depends_on:
      - elasticsearch
  logstash:
    image: 'logstash:7.13.3'
    container_name: logstash
    command: logstash -f /config/
    environment:
      - JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - '${LOGSTASH_CONFIG}:/config'
    networks:
      - elasticnetwork
    depends_on:
      - elasticsearch
      - redis

networks:
  elasticnetwork:
    driver: bridge
