version: "3"

services:
  mariadb:
    image: 'mariadb'
    container_name: 'mariadb'
    restart: 'always'
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ${MARIADB_DATA}:/var/lib/mysql
      - ${MARIADB_LOG}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    container_name: 'phpmyadmin'
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - '${PHPMYADMIN_PORT}:80'