version: '3'
services:
  client:
    container_name: client
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/data
    environment:
      - API_URL=http://localhost:8081/

  server:
    container_name: server
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/data
    depends_on:
      - server-database
    environment:
      - DATABASE_URL=server-database:27017

  server-database:
    container_name: server-database
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

  mariadb:
    image: mysql
    container_name: mariadb
    restart: always
    ports:
      - '${MARIADB_PORT}:3306'
    volumes:
      - '${MARIADB_DATA}:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MARIADB_DATABASE}'
      MYSQL_USER: '${MARIADB_USER}'
      MYSQL_PASSWORD: '${MARIADB_PASSWORD}'
    networks:
      - elasticnetwork

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - server-database
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MARIADB_ROOT_PASSWORD}'
      MYSQL_USER: '${MARIADB_USER}'
      MYSQL_PASSWORD: '${MARIADB_PASSWORD}'
    ports:
      - '${PHPMYADMIN_PORT}:80'
    networks:
      - elasticnetwork

  redis:
    container_name: redis
    image: redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - '${REDIS_DATA}:/data'
    networks:
      - elasticnetwork

  elasticsearch:
    image: 'elasticsearch:7.13.3'
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
    ports:
      - '${ELASTIC_PORT1}:9200'
      - '${ELASTIC_PORT2}:9300'
    volumes:
      - '${ELASTIC_CONFIG}:/usr/share/elasticsearch/config/elasticsearch.yml'
      - '${ELASTIC_DATA}:/usr/share/elasticsearch/data'
    networks:
      - elasticnetwork

  kibana:
    image: 'kibana:7.13.3'
    container_name: kibana
    ports:
      - '${KIBANA_PORT}:5601'
    volumes:
      - '${KIBANA_CONFIG}:/etc/kibana/kibana.yml'
    networks:
      - elasticnetwork
    depends_on:
      - elasticsearch

  logstash:
    image: 'logstash:7.13.3'
    container_name: logstash
    command: logstash -f /config/
    environment:
      - JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - '${LOGSTASH_CONFIG}:/config'
    networks:
      - elasticnetwork
    depends_on:
      - elasticsearch
      - redis

  postfixadmin:
    image: postfixadmin
    container_name: postfixadmin
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: mariadb
      POSTFIXADMIN_DB_USER: '${MARIADB_USER}'
      POSTFIXADMIN_DB_NAME: '${MARIADB_DATABASE}'
      POSTFIXADMIN_DB_PASSWORD: '${MARIADB_PASSWORD}'
      POSTFIXADMIN_SETUP_PASSWORD: 'Waseem66'
    ports:
      - "25:25"
      - "143:143"
      - "110:110"
      - "${POSTFIX_PORT}:80"
    depends_on:
      - mariadb
    networks:
      - elasticnetwork

networks:
  elasticnetwork:
    driver: bridge
